server:
  port: 8181
spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/my_postgres
    username: person
    password: person2002
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml